### ISSUE TITLE
can't process xml node with blanks

### ISSUE THREAD

**Issue by z16166** [rahra/libhpxml#1]
xml from docx sometimes contains blanks， with attr: xml:space="preserve"

<w:p w14:paraId="57D20C14" w14:textId="499AAE25" w:rsidR="00102269" w:rsidRDefault="00102269" w:rsidP="00102269">
<w:r>
<w:t>5303</w:t>
</w:r>
<w:r w:rsidR="008C6B14">
<w:t xml:space="preserve"> </w:t>
</w:r>
<w:r>
<w:t>4611</w:t>
</w:r>
<w:r w:rsidR="008C6B14">
<w:t xml:space="preserve"> </w:t>
</w:r>
<w:r>
<w:t>8488</w:t>
</w:r>
<w:r w:rsidR="008C6B14">
<w:t xml:space="preserve"> </w:t>
</w:r>
<w:r>
<w:t xml:space="preserve">7989 </w:t>
</w:r>
</w:p>

**Comment by rahra** [comment]
Unfortunately, that's not valid XML syntax. So if you have something linke `attr: xml:space="preserve"` with a space between `attr:` and `xml:space...` than these are two attribute value pairs. Meaning you get one item with `attr:` and then the next with `xml:space..`.

**Comment by rahra** [comment]
Where in this example from above does this occure? Or did you mean the keyword `space` is where this occurs?

**Comment by z16166** [comment]
Thank you for your quick response.

Sorry, the full xml node string should be:

<w:t xml:space="preserve"> </w:t>

It's from a Microsoft Word file(*.docx). You can rename the attached "PanTestv1.docx" file to "PanTestv1.zip" and unzip it with winrar/winzip to view the unzipped "word/document.xml".

And I have forked your repo to modify the code to deal with the xml attribute named "xml:space".
Please see whether my modification is ok if you have time. 
https://github.com/rahra/libhpxml/pull/2

Thanks!

[PanTestv1.docx](https://github.com/user-attachments/files/16690637/PanTestv1.docx)

**Comment by z16166** [comment]
I have more commits pending, please don't accept the PR. It's for review-only. thanks.

**Comment by rahra** [comment]
Sorry for late response. I will have a look at your docx to better understand the problem.

**Comment by rahra** [comment]
Ok I understood the problem. And actually my code violates the XML syntax since XML preserves white spaces in literal text between tags. This happens in `hpx_proc_buf()` and I will fix this. Unfortunately it's a little bit more subtle and just removing the "space-removal" is not enough since it should only be preserved if it's text in between an opening and a closing tag.
However, I'll fix it.

**Comment by rahra** [comment]
I just checked in a new branch (https://github.com/rahra/libhpxml/tree/dev) which should do the magic.

**Comment by rahra** [comment]
And I added support for CDATA elements and I fixed parsing of DOCTYPE subelements.

**Comment by z16166** [comment]
Thank you for your work. 

That PR is for review only and for my personal project, not meant to be merged.

I will try your new branch.
